### PR TITLE
pass additional options to simplecrawler

### PR DESCRIPTION
**Pull request by kbychkov**
It could be useful for guys who behind proxy like me to set HTTP/HTTPS agent. Although there is `useProxy` option also, but in my case that was not enough to pass the proxy.

### CODE REVIEW

**Comment by lgraubner** [comment]
Hi, thanks four your PR! I'm open to such a feature. Why is the `useProxy` option not sufficient? It is **not** included yet, but can be easily added. Did you see the corresponding options (`proxyHostname`, `proxyPort` etc.)?

**Comment by kbychkov** [comment]
Hello! Agree, `useProxy` could be userful as well. But when I worked with [SimpleCrawler](https://www.npmjs.com/package/simplecrawler) that didn't works. Our corporate proxy configured as HTTP for both HTTP and HTTPS requests. But SimpleCrawler doesn't take into account the proxy protocol. Instead it appends that based on requested URL. When URL is HTTPS it uses corresponding proxy protocol. Thus I was not able to crawl HTTPS sites. `useProxy` options works for HTTP sites, though.

After some search I've found [http-proxy-agent](https://www.npmjs.com/package/http-proxy-agent) and [https-proxy-agent](https://www.npmjs.com/package/https-proxy-agent) modules and was able to fix the problem with `httpAgent`, `httpsAgent` options.

**Comment by lgraubner** [comment]
That's indeed a problem. Could you add an example how to use it to the README? Would go for your suggested option as it seems more flexible.

**Comment by kbychkov** [comment]
Just added new options to the README. Hope it is descriptive enough.

**Comment by lgraubner** [comment]
Awesome, thanks!

**Pull request merged**
